# Generated by Django 3.1.2 on 2021-01-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Option', models.CharField(max_length=30)),
                ('questions', models.ImageField(upload_to='pics')),
                ('Topic', models.CharField(choices=[('Compiler Design', 'Compiler Design'), ('Computer Architecture', 'Computer Architecture'), ('Programming and Structures', 'Programming and Structures'), ('Algorithms', 'Algorithms'), ('Theory of Computation', 'Theory of Computation'), ('Operating System', 'Operating System'), ('Databases', 'Databases'), ('Computer Networks', 'Computer Networks'), ('Digital Logic', 'Digital Logic'), ('Discrete Mathematics', 'Discrete Mathematics'), ('Linear Algebra', 'Linear Algebra'), ('Calculus', 'Calculus'), ('Probability', 'Probability')], max_length=100)),
            ],
        ),
    ]
