# Generated by Django 3.1.2 on 2021-01-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Gate',
            field=models.CharField(choices=[('GATE_2019', 'GATE_2019')], default=None, max_length=100),
        ),
    ]
