# Generated by Django 3.1.2 on 2021-01-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Source', models.CharField(max_length=60)),
                ('Destination', models.CharField(max_length=60)),
                ('Amount', models.IntegerField()),
                ('Noon', models.CharField(max_length=5)),
            ],
        ),
    ]
