# Generated by Django 3.1.2 on 2021-01-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Destination',
            new_name='Activity',
        ),
        migrations.RemoveField(
            model_name='note',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='note',
            name='Noon',
        ),
        migrations.RemoveField(
            model_name='note',
            name='Source',
        ),
        migrations.AddField(
            model_name='note',
            name='Info',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='note',
            name='Status',
            field=models.CharField(default='Unfinished', max_length=30),
        ),
        migrations.AddField(
            model_name='note',
            name='Update',
            field=models.BooleanField(default=False),
        ),
    ]
